CREATE TABLE IF NOT EXISTS PRODUCTS(
    id SERIAL,
    productCode VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    image TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    stock INTEGER NOT NULL,
    description VARCHAR NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT products_id_pk
        PRIMARY KEY (id)
);